<?php defined('_ENGINE') or die('Access Denied'); return array (
  0 => 'Activity',
  1 => 'Album',
  2 => 'Announcement',
  3 => 'Authorization',
  4 => 'Blog',
  5 => 'Classified',
  6 => 'Core',
  7 => 'Elpis',
  8 => 'Fields',
  9 => 'Group',
  10 => 'Invite',
  11 => 'Messages',
  12 => 'Network',
  13 => 'Payment',
  14 => 'Seaocore',
  15 => 'Sitebooking',
  16 => 'Sitecore',
  17 => 'Sitecourse',
  18 => 'Storage',
  19 => 'User',
  20 => 'Video',
); ?>