<?php

/**
 * SocialEngineSolutions
 *
 * @category   Application_Sesbasic
 * @package    Sesbasic
 * @copyright  Copyright 2015-2016 SocialEngineSolutions
 * @license    http://www.socialenginesolutions.com/license/
 * @version    $Id: install.php 2015-07-25 00:00:00 SocialEngineSolutions $
 * @author     SocialEngineSolutions
 */
class Sesbasic_Installer extends Engine_Package_Installer_Module {

  public function onPreinstall() {

    $db = $this->getDb();

    parent::onPreinstall();
  }

  public function onInstall() {

    $db = $this->getDb();

    $bannedTable = $db->query('SHOW TABLES LIKE \'engine4_sesbasic_bannedwords\'')->fetch();
    if(empty($bannedTable)) {
      $db->query('CREATE TABLE IF NOT EXISTS `engine4_sesbasic_bannedwords` (
        `bannedword_id` int(10) unsigned NOT NULL auto_increment,
        `resource_type` varchar(32) CHARACTER SET latin1 COLLATE latin1_general_ci DEFAULT NULL,
        `resource_id` int(11) unsigned DEFAULT NULL,
        `word` text NOT NULL,
        PRIMARY KEY  (`bannedword_id`),
        KEY `resource_type` (`resource_type`, `resource_id`),
        UNIQUE KEY (`resource_type`, `resource_id`)
      ) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci;');
      $db->query("INSERT IGNORE INTO `engine4_sesbasic_bannedwords` (`word`,`resource_type`) VALUES
      ('help',''),
      ('activity',''),
      ('updates',''),
      ('messages',''),
      ('admin',''),
      ('user',''),
      ('members',''),
      ('wall',''),
      ('chat',''),
      ('about-us',''),
      ('stats',''),
      ('files',''),
      ('ads',''),
      ('invite',''),
      ('events',''),
      ('album',''),
      ('albums',''),
      ('classifieds',''),
      ('classified',''),
      ('content',''),
      ('forums',''),
      ('group',''),
      ('groups',''),
      ('blog',''),
      ('blogs',''),
      ('poll',''),
      ('polls',''),
      ('music',''),
      ('musics',''),
      ('video',''),
      ('videos',''),
      ('subscribes',''),
      ('tag',''),
      ('tags',''),
      ('tasks',''),
      ('profile',''),
      ('vote',''),
      ('core',''),
      ('fields',''),
      ('network',''),
      ('payment',''),
      ('sesactivitypoints',''),
      ('sesadvancedactivity',''),
      ('sesadvancedbanner',''),
      ('sesadvancedcomment',''),
      ('sesadvancedheader',''),
      ('sesadvminimenu',''),
      ('sesadvsitenotification',''),
      ('sesalbum',''),
      ('sesandroidapp',''),
      ('sesannouncement',''),
      ('sesapi',''),
      ('sesariana',''),
      ('sesarticle',''),
      ('sesblog',''),
      ('sesblogpackage',''),
      ('sesbody',''),
      ('sesbrowserpush',''),
      ('seschristmas',''),
      ('sescleanwide',''),
      ('sescommunityads',''),
      ('sescompany',''),
      ('sescontactus',''),
      ('sescontentcoverphoto',''),
      ('sescontest',''),
      ('sescontestjoinfees',''),
      ('sescontestjurymember',''),
      ('sescontestpackage',''),
      ('seselegant',''),
      ('sesemoji',''),
      ('seserror',''),
      ('sesevent',''),
      ('seseventcontact',''),
      ('seseventmusic',''),
      ('seseventpdfticket',''),
      ('seseventreview',''),
      ('seseventspeaker',''),
      ('seseventsponsorship',''),
      ('seseventticket',''),
      ('seseventvideo',''),
      ('sesexpose',''),
      ('sesfaq',''),
      ('sesfbstyle',''),
      ('sesfeedbg',''),
      ('sesfeedgif',''),
      ('sesfeelingactivity',''),
      ('sesfooter',''),
      ('sesgdpr',''),
      ('seshtmlbackground',''),
      ('seshtmlblock',''),
      ('seslangtranslator',''),
      ('sesletteravatar',''),
      ('seslink',''),
      ('sesmaterial',''),
      ('sesmember',''),
      ('sesmembershorturl',''),
      ('sesmetatag',''),
      ('sesminify',''),
      ('sesmultiplecurrency',''),
      ('sesmultipleform',''),
      ('sesmusic',''),
      ('sespage',''),
      ('sespagebuilder',''),
      ('sespageurl',''),
      ('sespoke',''),
      ('sesprayer',''),
      ('sesprofilelock',''),
      ('sesrecipe',''),
      ('sessiteiframe',''),
      ('sessociallogin',''),
      ('sessocialshare',''),
      ('sessocialtube',''),
      ('sesspectromedia',''),
      ('sestour',''),
      ('sestweet',''),
      ('sesusercoverphoto',''),
      ('sesusercovervideo',''),
      ('sesvideo',''),
      ('chanels',''),
      ('quotes',''),
      ('quote',''),
      ('prayers',''),
      ('prayer',''),
      ('page-directories',''),
      ('page-directory',''),
      ('browse-review',''),
      ('privacy-center',''),
      ('faqs',''),
      ('faq',''),
      ('events',''),
      ('eventmusics',''),
      ('eventmusic',''),
      ('comingsoon',''),
      ('contestpackage',''),
      ('contestpayment',''),
      ('contests',''),
      ('contest',''),
      ('wishes',''),
      ('friend-wishes',''),
      ('welcome',''),
      ('Sesblogs',''),
      ('blog-album',''),
      ('Sesarticles',''),
      ('article-album',''),
      ('articles',''),
      ('comment-like',''),
      ('comment',''),
      ('comments',''),
      ('app-default-data',''),
      ('stickers',''),
      ('feelings',''),
      ('onthisday',''),
      ('storage',''),
      ('page',''),
      ('stores',''),
      ('job-posting',''),
      ('level',''),
      ('likes',''),
      ('list',''),
      ('listing',''),
      ('listingitem',''),
      ('listingitems',''),
      ('listings',''),
      ('product',''),
      ('product-videos',''),
      ('products',''),
      ('market',''),
      ('media-importer',''),
      ('member',''),
      ('memberlevel',''),
      ('members-details',''),
      ('hashtag',''),
      ('hecore',''),
      ('hecore-friend',''),
      ('hecore-module',''),
      ('newsfeed',''),
      ('pdf',''),
      ('photo',''),
      ('points',''),
      ('pokes',''),
      ('profiletype',''),
      ('project',''),
      ('projects',''),
      ('qp',''),
      ('question',''),
      ('questions',''),
      ('radcodes',''),
      ('whcore',''),
      ('rss',''),
      ('sesbasic',''),
      ('settings',''),
      ('recipe',''),
      ('recipeitems',''),
      ('review-videos',''),
      ('reviews',''),
      ('xml',''),
      ('slideshow',''),
      ('writings','');");
    }

    parent::onInstall();
  }
}
